import type { Metadata } from 'next'
import './globals.css'
import { QueryProvider } from '@/provider/QueryProvider'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
    return (
        <html>
            <QueryProvider>
                <body>{children}</body>
            </QueryProvider>
        </html>
    )
}
